# Site settings
title: 深圳市物联网光子器件与传感系统重点实验室
subtitle: Key Lab of Photonic Devices and Sensing Systems for Internet of Things of Shenzhen
banner: szu-white.png
bannerlink: "http://www.szu.edu.cn"
email: ypwang@szu.edu.cn
author: 深圳市物联网光子器件与传感系统重点实验室
footer: "地址: &nbsp; 广东省深圳市南山区南海大道3688号 &nbsp; 深圳大学 &nbsp; 光电工程学院 &nbsp; 518060 &nbsp; Email: &nbsp; ypwang@szu.edu.cn &nbsp; 电话: &nbsp; 0755-26066281"
description: 2012年王义平教授入职深圳大学光电工程学院，在中国工程院院士牛憨笨教授的大力支持下，依托光学工程博士点和博士后流动站组建光纤传感技术研究团队和实验室。2014年王义平教授牵头组建的“深圳市物联网光子器件与传感系统重点实验室”获深圳市科技创新委员会批准立项建设。实验室现拥有百级超净实验室以及飞秒激光微加工系统、光纤光栅制备系统、微纳光纤拉制系统等1000余万元的仪器设备。实验室现有成员20人，其中教师2人、博士后5人、博士生3人、硕士生10人。
baseurl:
url: http://cofs.szu.edu.cn

navigation:
 - title: 实验室简介
   url: /intro
 - title: 研究方向
   url: /research
 - title: 团队成员
   url: /members
 - title: 论文专利
   url: /publications
 - title: 基金项目
   url: /fundings
 - title: 仪器设备
   url: /facilities
 - title: 团队风貌
   url: /gallery
 - title: 招生招聘
   url: /recruit

links:
 - title: "深圳大学"
   url: http://www.szu.edu.cn
 - title: "深圳大学光电工程学院"
   url: http://opto.szu.edu.cn
 - title: "英国南安普顿大学光电研究中心"
   url: http://www.orc.soton.ac.uk/
 - title: "香港理工大学"
   url: http://www.polyu.edu.hk/
 - title: "国家自然科学基金委"
   url: http://www.nsfc.gov.cn/
 - title: "深圳市科技创新委员"
   url: http://www.szsti.gov.cn/

newpapers:
 - name: "基于长周期光纤光栅和液体填充的光子晶体光纤折射率和温度同时传感"
   title: "Simultaneous Refractive Index and Temperature Measurement With LPFG and Liquid-Filled PCF"
   author: "Guolu Yin et al ,IEEE PHOTONICS TECHNOLOGY LETTERS, 27(4), 375-378, 2015"
   doc: "ygl-2015-Simultaneous Refractive Index and Temperature Measurement with LPFG and Liquid-Filled PCF1.pdf"
   image: ygl-2015.jpg
 - name: "非对称光纤马赫曾德干涉仪用于弯曲测量"
   title: "Asymmetrical in-fiber Mach-Zehnder interferometer for curvature measurement"
   author: "Bing Sun et al, OPTICS EXPRESS.23（11）14596-14602 DOI:10.1364/OE.23.014596"
   doc: "2015_OE_Asymmetrical in-fiber Mach-Zehnder interferometer for curvature measurement.pdf"
   image: sb-2015-923x400.jpg
 - name: "飞秒激光刻写高双折射相移布拉格光栅"
   title: "Highly birefringent phase-shifted fiber Bragg gratings inscribed with femtosecond laser"
   author: "Jun He et al,OPTICS LETTERS 40（9）2008-2011 2015."
   doc: "hj-2015-Highly birefringent phase-shifted fiber Bragg gratings inscribed with femtosecond laser 2015 (ol-40-9-2008).pdf"
   image: hj-2015.png

# Build settings
markdown: redcarpet  #kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

permalink: /news/:year-:month-:day-:title/
# paginate: 3
# paginate_path: "news/page:num"
# paginate_base: "news"
# pagiate_index: "news/index.html"
