
# Site settings
title: 广东省光纤传感技术粤港联合技术中心<br>深圳市物联网光子器件与传感系统重点实验室
subtitle: Shenzhen Key Lab of Photonic Devices and Sensing Systems for Internet of Things(PDSS)
banner: szu-white.png
bannerlink: "http://www.szu.edu.cn"
email: ypwang@szu.edu.cn
author: 深圳市物联网光子器件与传感系统重点实验室
footer: "地址: &nbsp; 广东省深圳市南山区南海大道3688号 &nbsp; 深圳大学 &nbsp; 光电工程学院 &nbsp; 518060 &nbsp; Email: &nbsp; ypwang@szu.edu.cn &nbsp; 电话: &nbsp; 0755-26066281"

baseurl:
url: http://cofs.szu.edu.cn

navigation:
 - title: 实验室简介
   url: /intro
 - title: 研究方向
   url: /research
 - title: 团队成员
   url: /members
 - title: 论文专利
   url: /publications
 - title: 人才培养
   url: /publications  
 - title: 基金项目
   url: /fundings
 - title: 仪器设备
   url: /facilities
 - title: 团队风貌
   url: /gallery
 - title: 招生招聘
   url: /recruit

links:
 - title: "深圳大学"
   url: http://www.szu.edu.cn
 - title: "深圳大学光电工程学院"
   url: http://opto.szu.edu.cn
 - title: "英国南安普顿大学光电研究中心"
   url: http://www.orc.soton.ac.uk/
 - title: "香港理工大学"
   url: http://www.polyu.edu.hk/
 - title: "国家自然科学基金委"
   url: http://www.nsfc.gov.cn/
 - title: "深圳市科技创新委员"
   url: http://www.szsti.gov.cn/

newpapers:
 - name: "基于CO2激光在空气芯光子带隙光纤中写制长周期光纤光栅气压传感器"
   title: "Gas pressure sensor based on CO2-laser-induced long period fiber grating in air-core photonic bandgap fiber"
   author: "Jian Tang et al,IEEE Photonics Journal, 7(5),6802207,2015."
   doc: "2015-12-PJ-Gas Pressure Sensor Based on CO 2-Laser-Induced Long-Period Fiber Grating in Air-Core Photonic Bandgap Fiber.pdf"
   image: tj-900x580.jpg
 - name: "基于带涂覆层单模光纤微环的高灵敏度温度传感器"
   title: "High-sensitivity temperature sensor based on a coated single-mode fiber loop"
   author: "Jun He et al, J. Lightwave Technol., 33(19), 4019-4026, 2015."
   doc: "2015-hj-jlt-33-19-4019.pdf"
   image: 2015-hj-jlp.jpg
 - name: "基于液晶填充的光子晶体光纤的宽带热光开关效应"
   title: "Broadband Thermo-Optic Switching Effect Based on Liquid Crystal Infiltrated Photonic Crystal Fibers"
   author: "Bing Sun et al,IEEE Photonics Journal, 7(4)，2015，6802207."
   doc: "sb-ieee-2015-Broadband Thermo-Optic Switching Effect Based on Liquid Crystal Infiltrated Photonic Crystal Fibers.pdf"
   image: sb-ieee.png
 
# Build settings
markdown: redcarpet  #kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

permalink: /news/:year-:month-:day-:title/
# paginate: 3
# paginate_path: "news/page:num"
# paginate_base: "news"
# pagiate_index: "news/index.html"
