# Site settings
title: 深圳大学光纤传感研究中心
subtitle: Center for Optical Fiber Sensors of Shenzhen University
banner: cofs-logo-s-112x112.jpg
bannerlink: "http://cofs.szu.edu.cn"
email: xiaofeng.qu.hk@ieee.org
author: Xiaofeng QU
footer: "地址: &nbsp; 广东省深圳市南山区南海大道3688号 &nbsp; 深圳大学 &nbsp; 光电工程学院 &nbsp; 518060 &nbsp; Email: &nbsp; ypwang@szu.edu.cn &nbsp; 电话: &nbsp; 0755-26066281"
description: 深圳大学光纤传感研究中心成立于2012年，是王义平教授在中国工程院院士牛憨笨教授的大力支持下，依托光电工程学院光学工程学科和“光电子器件与系统教育部重点实验室”组建而成。研究中心目前已购置飞秒激光器、纳米级电动平移台、光纤偏振分析系统、全自动光纤侧抛系统等约1000万元的仪器设备。研究中心现有成员20人（教师2人、博士后5人、博士生4人、硕士生11人）。研究中心研究方向主要集中在微纳加工技术、微纳光子器件及应用、光纤生化传感技术等。
baseurl: 
url: http://fibersensors.tk

navigation:
 - title: 研究方向
   url: /research
 - title: 团队成员
   url: /members
 - title: 论文专利
   url: /publications
 - title: 项目基金
   url: /fundings
 - title: 仪器设备
   url: /facilities
 - title: 团队影集
   url: /gallery
 - title: 招生招聘
   url: /recruit

links:
 - title: "靳伟教授"
   url: http://myweb.polyu.edu.hk/~eewjin
 - title: "浙大现代光学仪器国家重点实验室"
   url: http://www.nanophotonics.zju.edu.cn/Web_Tong
 - title: "华中科技大学超快光学实验室"
   url: http://ufolab.phys.hust.edu.cn
 - title: "深圳大学"
   url: http://www.szu.edu.cn
 - title: "深圳大学光电工程学院"
   url: http://opto.szu.edu.cn

newpapers:
 - title: "Long Period Fiber Gratings Inscribed With an Improved Two-Dimensional Scanning Technique"
   author: "X. Zhong et al., IEEE Photonics Journal (2014)."
   doc: "[3]-Long period fiber gratings inscribed with an improved two-dimensional scanning technique.pdf"
 - title: "Ultrasensitive refractive index sensor based on a Mach–Zehnder interferometer created in twin-core fiber"
   author: "Z. Li et al., Optics Letters (2014)."
   doc: "[4]-Ultrasensitive refractive index sensor.pdf"
 - title: "Sub-micron silica diaphragm based fiber-tip Fabry-Perot interferometer for pressure measurement"
   author: "C. Liao et al., Optics Letters (2014)."
   doc: "changruiliao2014opticsletters.pdf"
 - title: "Temperature-insensitive refractive index sensor based on in-fiber Michelson interferometer"
   author: "Z. Li et al., Sensors and Actuators B: Chemical (2014)."
   doc: "[6]-Temperature-insensitive refractive index sensor based on in-fiber Michelson interferometer.pdf"

# Build settings
markdown: redcarpet  #kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

permalink: /news/:year-:month-:day-:title/
# paginate: 3
# paginate_path: "news/page:num"
# paginate_base: "news"
# pagiate_index: "news/index.html"
